// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7PD9ZOfaCvcGI-XZBifW7BSB97EIcvAg',
    appId: '1:456779727649:web:8d04f8a14714884342b460',
    messagingSenderId: '456779727649',
    projectId: 'test121244',
    authDomain: 'test121244.firebaseapp.com',
    storageBucket: 'test121244.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHRbpg8jo46thFJ7PKMdp9JV0ycbnaG2k',
    appId: '1:456779727649:android:30713113a098a7fb42b460',
    messagingSenderId: '456779727649',
    projectId: 'test121244',
    storageBucket: 'test121244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1IzIRgTl7ZNrLtUVr7zKyhnsC1FbNuMI',
    appId: '1:456779727649:ios:97e1cd31dad4950642b460',
    messagingSenderId: '456779727649',
    projectId: 'test121244',
    storageBucket: 'test121244.firebasestorage.app',
    iosBundleId: 'com.minchan.gorouterdeeplink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1IzIRgTl7ZNrLtUVr7zKyhnsC1FbNuMI',
    appId: '1:456779727649:ios:97e1cd31dad4950642b460',
    messagingSenderId: '456779727649',
    projectId: 'test121244',
    storageBucket: 'test121244.firebasestorage.app',
    iosBundleId: 'com.minchan.gorouterdeeplink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7PD9ZOfaCvcGI-XZBifW7BSB97EIcvAg',
    appId: '1:456779727649:web:7898061e4d376a5342b460',
    messagingSenderId: '456779727649',
    projectId: 'test121244',
    authDomain: 'test121244.firebaseapp.com',
    storageBucket: 'test121244.firebasestorage.app',
  );
}
